-- INSERT INTO department (department_name)
-- VALUES
--     ('Marketing'),
--     ('Production'),
--     ('Development'),
--     ('Accounting'),
--     ('Executive');

-- INSERT INTO job_title (title, salary, department_id)
-- VALUES
--     ('Marketing Director', 200000.00, 1),
--     ('Marketing Regional Manager', 150000.00, 1),
--     ('Marketing Branch Executive', 125000.00, 1),
--     ('Marketing Team Leader', 90000.00, 1),
--     ('Marketing Associate', 75000.00, 1),
--     ('Marketing Trainee', 50000.00, 1),
--     ('Production Director', 250000.00, 1),
--     ('Production Regional Manager', 190000.00, 2),
--     ('Production Project Director', 150000.00, 2),
--     ('Production Team Leader', 75000.00, 2),
--     ('Production Shift Coordinator', 60000.00, 2),
--     ('Production Member', 50000.00, 2),
--     ('Development Director', 225000.00, 3),
--     ('Development Regional Manager', 185000.00, 3),
--     ('Development Branch Executive', 145000.00, 3),
--     ('Development Team Leader', 100000.00, 3),
--     ('Development Research Associate', 80000.00, 3),
--     ('Development Research Assistant', 60000.00, 3),
--     ('Chief Financial Officer', 250000.00, 4),
--     ('Accounting Regional Manager', 175000.00, 4),
--     ('Accounting Branch Executive', 130000.00, 4),
--     ('Accounting Team Leader', 100000.00, 4),
--     ('Accountant', 85000.00, 4),
--     ('Accounting Assistant', 65000.00, 4),
--     ('Chief Executive Officer', 300000.00, 5),
--     ('Chief Executive Assistant', 70000.00, 5);

INSERT INTO manager (name)
    VALUES 
        ('Charles Burns'),
        ('Ronald Firbank'),
        ('Virginia Woolf'),
        ('Piers Gaveston'),
        ('Charles LeRoi'),
        ('Katherine Mansfield'),
        ('Dora Carrington'),
        ('Edward Bellamy'),
        ('Montague Summers'),
        ('Octavia Butler'),
        ('Unica Zurn'),
        ('James Fraser'),
        ('Jack London'),
        ('Robert Bruce'),
        ('Peter Greenaway'),
        ('Derek Jarman'),
        ('Paolo Pasolini'),
        ('Heathcote Williams'),
        ('Sandy Powell'),
        ('Emil Zola'),
        ('Sissy Coalpits'),
        ('William Morris'),
        ('George Shaw'),
        ('Arnold Bennett'),
        ('Algernon Blackwood'),
        ('Rhoda Broughton'),
        ('Hart Crane'),
        ('Vitorio DeSica'),
        ('Wilkie Collins'),
        ('Elizabeth Gaskell'),
        ('George Sand'),
        ('Vernon Lee'),
        ('Walter Becker'),
        ('Jeff Baxter'),
        ('David Palmer'),
        ('Denny Dias'),
        ('Michael McDonald'),
        ('Burton Cummings'),
        ('Bob Seger'),
        ('Kevin Cronin'),
        ('Karen Carpenter'),
        ('Ingrid Bergman'),
        ('Sally Field'),
        ('Kate Winslet'),
        ('Diane Lane'),
        ('Emma Stone'),
        ('Hailee Steinfeld'),
        ('Walt Whitman'),
        ('Henry Thoreau');

INSERT INTO employee (first_name, last_name, job_title_id, manager_id)
VALUES
    ('Charles', 'Burns', 25, NULL),
    ('Ronald', 'Firbank', 1, 1),
    ('Virginia', 'Woolf', 7, 1),
    ('Piers', 'Gaveston', 13, 1),
    ('Charles', 'LeRoi', 19, 1),
    ('Katherine', 'Mansfield', 2, 2),
    ('Dora', 'Carrington', 2, 2),
    ('Edward', 'Bellamy', 8, 3),
    ('Montague', 'Summers', 8, 3),
    ('Octavia', 'Butler', 14, 4),
    ('Unica', 'Zurn', 14, 4),
    ('James', 'Fraser', 20, 5 ),
    ('Jack', 'London', 20, 5),
    ('Robert', 'Bruce', 3, 6),
    ('Peter', 'Greenaway', 3, 6),
    ('Derek', 'Jarman', 3, 7),
    ('Paolo', 'Pasolini', 4, 14),
    ('Heathcote', 'Williams', 4, 15),
    ('Sandy', 'Powell', 4, 15),
    ('Emil', 'Zola', 4, 16),
    ('Sissy', 'Coalpits', 4, 16),
    ('Antoinette', 'Capet', 5, 17),
    ('Samuel', 'Delany', 5, 18),
    ('Tony', 'Duvert', 5, 18),
    ('Dennis', 'Cooper', 5, 19),
    ('Monica', 'Bellucci', 5, 19),
    ('Samuel', 'Johnson', 5, 20),
    ('John', 'Dryden', 5, 20),
    ('Alexander', 'Pope', 5, 21),
    ('Lionel', 'Johnson', 6, 17),
    ('Aubrey', 'Beardsley', 6, 18),
    ('Tulse', 'Luper', 6, 21),
    ('William', 'Morris', 9, 8),
    ('George', 'Shaw', 9, 8),
    ('Arnold', 'Bennett', 9, 9),
    ('Algernon', 'Blackwood', 9, 9),
    ('Rhoda', 'Broughton', 9, 9),
    ('Hart', 'Crane', 10, 22),
    ('Vitorio', 'DeSica', 10, 23),
    ('Wilkie', 'Collins', 10, 23),
    ('Elizabeth', 'Gaskell', 10, 24),
    ('George', 'Sand', 10, 25),
    ('Vernon', 'Lee', 10, 26),
    ('Arthur', 'Machen', 11, 27),
    ('Frederick', 'Marryat', 11, 27),
    ('Harriet', 'Martineau', 11, 28),
    ('George', 'Meredith', 11, 28),
    ('Margaret', 'Oliphant', 11, 29),
    ('Anthony', 'Trollope', 11, 30),
    ('Charlotte', 'Yonge', 11, 31),
    ('Horace', 'Walpole', 11, 32),
    ('Matthew', 'Lewis', 11, 32),
    ('William', 'Bedford', 12, 27),
    ('Anne', 'Radcliffe', 12, 27),
    ('Charles', 'Brown', 12, 28),
    ('Eliza', 'Parsons', 12, 28),
    ('Susan', 'Hill', 12, 29),
    ('Sydney', 'Owenson', 12, 29),
    ('Hubert', 'Crackanthorpe', 12, 30),
    ('William', 'Carleton', 12, 30),
    ('Gerald', 'Griffin', 12, 30),
    ('John', 'Lennon', 12, 31),
    ('Paul', 'McCartney', 12, 31),
    ('George', 'Harrison', 12, 31),
    ('Richard', 'Starkey', 12, 32),
    ('Donald', 'Fagan', 12, 32),
    ('Walter', 'Becker', 15, 10),
    ('Jeff', 'Baxter', 15, 11),
    ('David', 'Palmer', 15, 11),
    ('Denny', 'Dias', 16, 33),
    ('Michael', 'McDonald', 16, 33),
    ('Burton', 'Cummings', 16, 34),
    ('Bob', 'Seger', 16, 34),
    ('Kevin', 'Cronin', 16, 35),
    ('Karen', 'Carpenter', 16, 35),
    ('Mark', 'Farner', 17, 36),
    ('Linda', 'Ronstadt', 17, 37),
    ('Patsy', 'Cline', 17, 37),
    ('Stefani', 'Germanotta', 17, 38),
    ('J.K.', 'Rowling', 17, 38),
    ('J.R.R.', 'Tolkien', 17, 39),
    ('Willa', 'Cather', 17, 39),
    ('Mary', 'Shelley', 17, 40),
    ('Stephen', 'King', 17, 40),
    ('Pearl', 'Buck', 17, 41),
    ('Sandra', 'Bullock', 17, 41),
    ('Han', 'Solo', 18, 36),
    ('Meryl', 'Streep', 18, 37),
    ('Ingrid', 'Bergman', 21, 12),
    ('Sally', 'Field', 21, 12),
    ('Kate', 'Winslet', 21, 13),
    ('Diane', 'Lane', 22, 42),
    ('Emma', 'Stone', 22, 42),
    ('Hailee', 'Steinfeld', 22, 43),
    ('Walt', 'Whitman', 22, 43),
    ('Henry', 'Thoreau', 22, 44),
    ('Rich', 'Roll', 23, 45),
    ('Don', 'Henley', 23, 46),
    ('Luke', 'Skywalker', 23, 47),
    ('Illyana', 'Rasputin', 23, 48),
    ('Ororo', 'Munroe', 23, 49),
    ('Anna', 'Marie', 23, 49),
    ('Jean', 'Grey', 24, 45),
    ('Homer', 'Simpson', 24, 46),
    ('Waylon', 'Smithers', 25, 1);
    

    